### ISSUE TITLE
应用流水线，可以将构建镜像选择镜像语言的构建环境和应用开发语言合并，使用开发语言的构建环境，这边只选择版本

### ISSUE THREAD

**Issue by GeorGeWzw** [KubeLilin/kubelilin#22]
![image](https://user-images.githubusercontent.com/46982191/208627408-a617bbaf-947e-49ed-8b47-9300654db85c.png)

**Comment by yoyofx** [comment]
收到

**Comment by yoyofx** [comment]
已修改为 流水线默认语言与应用语言相同，但可修改。
