### ISSUE TITLE
网络中心-服务Service 选择 namespace后显示不正常

### ISSUE THREAD

**Issue by yoyofx** [KubeLilin/kubelilin#29]
应该按 应用,部署 进行选择，只能显示平台创建的service, 应用内可跳转到 此页面

**Comment by yoyofx1** [comment]
Service 只显示租户自己的服务

**Comment by Artanis-c** [comment]
service是按命名空间进行区分的，不同的租户应该属于不同的命名空间，应该从这一层开始区分，而不是在这服务这进行划分
