### ISSUE TITLE
部署名称不能出现大写

### ISSUE THREAD

**Issue by yoyofx** [KubeLilin/kubelilin#31]
部署名称 只能是 小写字母  "-" 字符.

**Comment by Artanis-c** [comment]
已修复

**Comment by yoyofx** [comment]
![image](https://github.com/KubeLilin/kubelilin/assets/4504853/131e0c1a-ae1c-462b-ab24-dea8ba952ea9)

**Comment by yoyofx** [comment]
高级部署也需要修改

**Comment by yoyofx** [comment]
除命名规范外，将部署名称设置为 appName+nickname ，方便后面实现集群迁移的功能。
