### ISSUE TITLE
项目创建成功后,没有刷新列表

### ISSUE THREAD

**Issue by wmowm** [KubeLilin/kubelilin#32]
![image](https://github.com/KubeLilin/kubelilin/assets/16713889/ebec6042-21d5-471a-8443-653ec26fdd67)
![image](https://github.com/KubeLilin/kubelilin/assets/16713889/34a9d542-23e2-455a-8ad2-119337ddf628)

**Comment by yoyofx** [comment]
已修复。  创建和更新后都不会刷新列表
