### ISSUE TITLE
项目管理->创建应用,名称只允许输入英文

### ISSUE THREAD

**Issue by wmowm** [KubeLilin/kubelilin#33]
![image](https://github.com/KubeLilin/kubelilin/assets/16713889/e6654921-ec28-4fd5-bce6-b347298243c0)
还有其它位置的名称,应该支持字母,数字, - _ . 映射到k8s的yaml文件,需要遵循k8s规范,将特殊符号进行替换

**Comment by yoyofx** [comment]
fixed

**Comment by yoyofx** [comment]
小写字母、数字、-
