### ISSUE TITLE
编辑构建,选择构建环境,构建的下拉框没有同步修改

### ISSUE THREAD

**Issue by wmowm** [KubeLilin/kubelilin#36]
![image](https://github.com/KubeLilin/kubelilin/assets/16713889/c28c78dd-5aac-47cf-9633-1e50a1a974f0)

先选择一个构建环境, 选择构建镜像,切换构建环境

**Comment by Artanis-c** [comment]
bug已修复，现在下拉框会根据选择的语言变更默认选项
