### ISSUE TITLE
添加应用别名(必填项),并在应用列表中显示

### ISSUE THREAD

**Issue by wmowm** [KubeLilin/kubelilin#37]
![image](https://github.com/KubeLilin/kubelilin/assets/16713889/16eb2866-98ba-448b-a20a-898f4cd65e40)
在应用已经创建的情况下,修改应用名称

**Comment by Artanis-c** [comment]
bug已修复

**Comment by yoyofx** [comment]
设计上:  部署标识= 应用名+部署名 + 集群名
应用名称作为系统唯一标识,不能在后端被修改.  

修改建议:
前端禁用编辑应用名称(置灰) , 编辑时后端不能更新应用名称字段.   应添加描述字段如 nick_name 来用于显示中文描述来代替应用名称给用户的提示性作用.

**Comment by Artanis-c** [comment]
fixing
